/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/analyze/album": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Analyze Album
         * @description Analiza una URL de álbum y extrae su metadata y lista de pistas.
         *
         *     Args:
         *         url (str): URL proporcionada por el usuario.
         *         yt_service (YouTubeService): Servicio de YouTube inyectado.
         *
         *     Returns:
         *         AlbumResponse: Objeto con la información del álbum.
         *
         *     Raises:
         *         HTTPException: Si la URL no es válida o no se encuentra el álbum.
         */
        get: operations["analyze_album_api_v1_analyze_album_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/download/album": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Download
         * @description Inicia el proceso de descarga en segundo plano y asocia el progreso al job_id.
         */
        post: operations["start_download_api_v1_download_album_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/download/album/zip/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Album Zip
         * @description Busca el resultado de un job finalizado, comprime los archivos y los sirve.
         */
        get: operations["download_album_zip_api_v1_download_album_zip__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current Settings
         * @description Retorna la configuración actual procesada por la aplicación.
         *
         *     Args:
         *         settings (AppSettings): Instancia única de configuración.
         *
         *     Returns:
         *         dict: Diccionario con los valores actuales de configuración.
         */
        get: operations["get_current_settings_api_v1_settings__get"];
        put?: never;
        /**
         * Update Settings
         * @description Actualiza el archivo .env persistente con los nuevos valores proporcionados.
         *
         *     Args:
         *         new_data (Dict[str, str]): Diccionario con las llaves y valores a modificar.
         *         settings (AppSettings): Instancia única de configuración.
         *
         *     Returns:
         *         dict: Mensaje de confirmación.
         *
         *     Raises:
         *         HTTPException: Si ocurre un error al escribir el archivo.
         */
        post: operations["update_settings_api_v1_settings__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/check/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint para verificar que la API está funcionando.
         */
        get: operations["health_check_api_v1_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AlbumResponse
         * @description Modelo de respuesta para los detalles de un álbum.
         *
         *     Attributes:
         *         response_type (ResponseType): El tipo de respuesta (album).
         *         title (str): El título del álbum.
         *         youtube_type (str): El tipo de contenido en YouTube (por ejemplo, "album").
         *         is_explicit (bool): Indica si el álbum es explícito.
         *         description (str): La descripción del álbum.
         *         year (int): El año de lanzamiento del álbum.
         *         artists (List[str]): Los artistas del álbum.
         *         track_count (int): El número de canciones en el álbum.
         *         thumbnail (HttpUrl): La URL de la miniatura del álbum.
         *         tracks (List[AlbumTrackResponse]): Los detalles de las canciones del álbum.
         */
        "AlbumResponse-Input": {
            /** @default album */
            response_type: components["schemas"]["ResponseType"];
            /** Title */
            title?: string | null;
            /** Youtube Type */
            youtube_type?: string | null;
            /** Is Explicit */
            is_explicit?: boolean | null;
            /** Description */
            description?: string | null;
            /** Year */
            year: number;
            /**
             * Artists
             * @default []
             */
            artists: string[];
            /** Track Count */
            track_count: number;
            /** Thumbnail */
            thumbnail?: string | null;
            /**
             * Tracks
             * @default []
             */
            tracks: components["schemas"]["AlbumTrackResponse"][];
        };
        /**
         * AlbumResponse
         * @description Modelo de respuesta para los detalles de un álbum.
         *
         *     Attributes:
         *         response_type (ResponseType): El tipo de respuesta (album).
         *         title (str): El título del álbum.
         *         youtube_type (str): El tipo de contenido en YouTube (por ejemplo, "album").
         *         is_explicit (bool): Indica si el álbum es explícito.
         *         description (str): La descripción del álbum.
         *         year (int): El año de lanzamiento del álbum.
         *         artists (List[str]): Los artistas del álbum.
         *         track_count (int): El número de canciones en el álbum.
         *         thumbnail (HttpUrl): La URL de la miniatura del álbum.
         *         tracks (List[AlbumTrackResponse]): Los detalles de las canciones del álbum.
         */
        "AlbumResponse-Output": {
            /** @default album */
            response_type: components["schemas"]["ResponseType"];
            /** Title */
            title?: string | null;
            /** Youtube Type */
            youtube_type?: string | null;
            /** Is Explicit */
            is_explicit?: boolean | null;
            /** Description */
            description?: string | null;
            /** Year */
            year: number;
            /**
             * Artists
             * @default []
             */
            artists: string[];
            /** Track Count */
            track_count: number;
            /** Thumbnail */
            thumbnail?: string | null;
            /**
             * Tracks
             * @default []
             */
            tracks: components["schemas"]["AlbumTrackResponse"][];
        };
        /**
         * AlbumTrackResponse
         * @description Modelo de respuesta para los detalles de una canción extraída desde el link de un álbum.
         *
         *     Attributes:
         *         response_type (ResponseType): El tipo de respuesta (album_track).
         *         video_id (str): El ID del video en YouTube.
         *         title (str): El título de la canción.
         *         artists (List[str]): Los artistas de la canción.
         *         album (str): El nombre del álbum.
         *         track_number (int): El número de la canción en el álbum.
         *         url_canonical (HttpUrl): La URL canónica de la canción.
         *         thumbnail (HttpUrl): La URL de la miniatura de la canción.
         *         length_seconds (int): La duración de la canción en segundos.
         *         duration_seconds (int): La duración de la canción en segundos.
         *         duration_iso (str): La duración de la canción en formato ISO 8601.
         *         category (str): La categoría de la canción.
         *         publish_date (date): La fecha de publicación de la canción.
         *         upload_date (datetime): La fecha y hora de subida de la canción a YouTube.
         *         year (int): El año de lanzamiento del álbum.
         *         total_tracks (int): El número total de canciones en el álbum.
         */
        AlbumTrackResponse: {
            /** @default album_track */
            response_type: components["schemas"]["ResponseType"];
            /** Video Id */
            video_id: string;
            /** Title */
            title: string;
            /**
             * Artists
             * @default []
             */
            artists: string[];
            /** Album */
            album?: string | null;
            /** Track Number */
            track_number?: number | null;
            /** Url Canonical */
            url_canonical?: string | null;
            /** Thumbnail */
            thumbnail?: string | null;
            /** Length Seconds */
            length_seconds?: number | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /** Duration Iso */
            duration_iso?: string | null;
            /** Category */
            category?: string | null;
            /** Publish Date */
            publish_date?: string | null;
            /** Upload Date */
            upload_date?: string | null;
            /** Year */
            year?: number | null;
            /** Total Tracks */
            total_tracks?: number | null;
        };
        /**
         * Bitrate
         * @description Enum para los bitrates
         *
         *     Attributes:
         *         B_48K (str): 48Kbps
         *         B_56K (str): 56Kbps
         *         B_64K (str): 64Kbps
         *         B_96K (str): 96Kbps
         *         B_128K (str): 128Kbps
         *         B_192K (str): 192Kbps
         *         B_256K (str): 256Kbps
         *         B_320K (str): 320Kbps
         * @enum {string}
         */
        Bitrate: "48k" | "56k" | "64k" | "96k" | "128k" | "192k" | "256k" | "320k";
        /**
         * DownloadRequest
         * @description Objeto para solicitar la descarga de un álbum filtrado.
         *
         *     Attributes:
         *         job_id (UUID): Identificador único de la solicitud de descarga.
         *         album_data (AlbumResponse): Datos del álbum filtrado. Contiene los tracks ya filtrados/seleccionados por el frontend
         *         genre (Optional[str]): Género musical para asignar a los tracks del album.
         *         bitrate (Bitrate): Bitrate para asignar a los tracks del album. Por defecto es B_128K (128kbps).
         *         format (Format): Formato de descarga de los tracks del album. Por defecto es MP3.
         */
        DownloadRequest: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            album_data: components["schemas"]["AlbumResponse-Input"];
            /** @default mp3 */
            format: components["schemas"]["Format"];
            /** @default 128k */
            bitrate: components["schemas"]["Bitrate"];
            /** Genre */
            genre?: string | null;
        };
        /**
         * Format
         * @description Enums para los formatos de audio.
         *
         *     Attributes:
         *         MP3 (str): MP3
         *         WAV (str): WAV
         *         FLAC (str): FLAC
         *         OGG (str): OGG
         *         OPUS (str): OPUS
         *         AAC (str): AAC
         *         AIFF (str): AIFF
         *         M4A (str): M4A
         *         M4B (str): M4B
         * @enum {string}
         */
        Format: "mp3" | "wav" | "flac" | "ogg" | "opus" | "aac" | "aiff" | "m4a" | "m4b";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ResponseType
         * @description Enum que representa los tipos de respuesta para las solicitudes de descarga de música.
         *
         *     Attributes:
         *         PLAYLIST (str): Indica que la respuesta es para una playlist.
         *         TRACK (str): Indica que la respuesta es para una pista individual.
         *         ARTIST (str): Indica que la respuesta es para un artista.
         *         ALBUM (str): Indica que la respuesta es para un álbum.
         *         PLAYLIST_TRACK (str): Indica que la respuesta es para una canción que se extrajo desde el link de una playlist.
         *         ARTIST_TRACK (str): Indica que la respuesta es para una canción que se extrajo desde el link de un artista.
         *         ALBUM_TRACK (str): Indica que la respuesta es para una canción que se extrajo desde el link de un álbum.
         * @enum {string}
         */
        ResponseType: "playlist" | "track" | "artist" | "album" | "playlist_track" | "artist_track" | "album_track";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    analyze_album_api_v1_analyze_album_get: {
        parameters: {
            query: {
                /** @description URL de la playlist del álbum en YouTube Music */
                url: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlbumResponse-Output"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_download_api_v1_download_album_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DownloadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_album_zip_api_v1_download_album_zip__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_settings_api_v1_settings__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    update_settings_api_v1_settings__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: string;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_api_v1_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
